default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: Tweeters_Digest_API_development

test:
  <<: *default
  database: Tweeters_Digest_API_test

production:
  <<: *default
  database: Tweeters_Digest_API_production
  username: Tweeters_Digest_API
  password: <%= ENV['TWEETERS_DIGEST_API_DATABASE_PASSWORD'] %>
